### ISSUE TITLE
Matthew needs to give everyone commit access

### ISSUE THREAD

**Issue by matthewsot** [matthewsot/cs197-systems#1]
Please comment below and I'll add you to the repo!

Maybe include something fun w/ your comment as a little intro activity? Maybe an (**appropriate** please!) meme you enjoyed recently? Favorite cat photo? Recent song discovery? Favorite algorithm/theorem/codebase? Up to you !

![image](https://user-images.githubusercontent.com/1159057/193190368-c79e9380-ca80-4a2f-829e-a15b5c832991.png)

**Comment by ihyunnam** [comment]
Hi this is Ihyun!

**Comment by sophiejandrews** [comment]
Hi this is Sophie!

**Comment by jmerch** [comment]
Hi everyone! This is Jonathan.

**Comment by santiramos27** [comment]
Hi, this is Santino! Here's a [theorem with a funny name](https://artofproblemsolving.com/wiki/index.php/Chicken_McNugget_Theorem).

**Comment by sxiao101** [comment]
Hi, this is Shannon!

**Comment by Tweoss** [comment]
Hoi, this is Francis. My favorite desktop wallpaper:
![rust go bg](https://user-images.githubusercontent.com/70821802/193367356-be5b8023-d051-4396-bebd-ae86fb10cf13.jpeg)

**Comment by salman-abd** [comment]
Hi, this is Salman

**Comment by usmantariq25** [comment]
Hi everyone, this is Usman.

**Comment by Kelvin-Waititu** [comment]
Hi everyone, this Kelvin.
